add_newline = false
format = "$character$directory$all"

[line_break]
disabled = true

[character]                            
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[cmd_duration]
disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 1

[git_branch]
format = "[git:\\([$branch](bold red)\\)](bold blue) [$symbol](bold yellow) "
symbol = "✗"

[package]
disabled = true
